### PR TITLE
Fix for logrotate.d template

### PR DESCRIPTION
**Pull request by radoslawd**

### CODE REVIEW

**Comment by JamesBelchamber** [comment]
I think you're suffering from this issue not because of a bug in the code, but because you're using an old version of jinja2. The `mapping()` test was introduced in Jinja 2.6.

If I introduce this change I think it would fail on a string, but I'm not 100% on that. I'll test it later today :)

**Comment by radoslawd** [comment]
Well, as I can see, we're using Jinja 2.7.2.

**Comment by JamesBelchamber** [comment]
Hmm. So if you pass a variable into this code that looks like a list:

```
logrotate_applications:
  - name: syslog
    path:
    - "/var/log/cron"
    - "/var/log/maillog"
```

Then that code path shouldn't even be activated, it should use the for loop (lines 2-4) instead. That bit of code you changed should only be used if `path` is a string (or at least, not a list). A good reason for that code path being activated is that the `mapping()` test it does on line 1 is failing because `mapping()` doesn't exist in your version of jinja. There could be another reason why that test is failing - what I can say is that it doesn't fail in my tests locally.

I'm happy to fix this bug, I want to know why it's happening for you and not for me first!

**Comment by JamesBelchamber** [comment]
Is this still an issue for you @radoslawd ?

**Pull request closed without merging**
